name: Execute Wikipedia Script

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "45 5 * * *"

jobs:
  formatting-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Super Linter
        uses: super-linter/super-linter/slim@v7.0.0
        env:
          DEFAULT_BRANCH: main
          SAVE_SUPER_LINTER_OUTPUT: true
          VALIDATE_PYTHON_ISORT: true
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_ALL_CODEBASE: false
          IGNORE_GITIGNORED_FILES: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-formatting-validation-result:
    needs:
      - formatting-check
    if: always()
    runs-on: ubuntu-latest
    steps:
      - if: (needs.formatting-check.result == 'failure' || needs.formatting-check.result == 'cancelled')
        run: echo "fail or cancelled" && exit 1
      - if: (needs.formatting-check.result == 'success' || needs.formatting-check.result == 'skipped')
        run: echo "success" && exit 0

  formatting-fix:
    needs:
      - formatting-check
      - check-formatting-validation-result
    if: always() && needs.check-formatting-validation-result.result == 'failure'
    permissions:
      contents: write
      statuses: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Print validation result
        run: |
          echo "$needs.formatting-check.result"
      - name: Super Linter
        uses: super-linter/super-linter@v7.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON_ISORT: true
          FIX_PYTHON_ISORT: true
          VALIDATE_PYTHON_BLACK: true
          FIX_PYTHON_BLACK: true
      - name: Commit and push fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: fix linting issues"
          commit_user_name: super-linter
          commit_user_email: super-linter@super-linter.dev

  build-and-run:
    runs-on: ubuntu-latest
    needs:
      - formatting-fix
    if: always()
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Print Current Time
        run: |
          echo "Current time: $(date)"
          echo "Current time (UTC): $(date -u)"
          echo "TimeZone: $TZ"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip --version
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest

      - name: Run Wikipedia UUID Script
        run: python3 -m scripts.wikipedia_uuid
